### ISSUE TITLE
Incorrect import statement in `container_bindings_middleware.ts`

### ISSUE THREAD

**Issue by conghuyn** [adonisjs/slim-starter-kit#5]
### Package version

Unknown

### Describe the bug

I have identified an issue with an import statement in the **app/middleware/container_bindings_middleware.ts** file.
The current import statement is as follows:
`import { NextFn } from '@adonisjs/core/types/http'`

However, it should be updated to use TypeScript's import type syntax to correctly signify that NextFn is a type-only import. The corrected import statement should be:
`import type { NextFn } from '@adonisjs/core/types/http'`

**Comment by RomainLanz** [comment]
Hey @huync16! 👋🏻 

Could you please make a PR?

**Comment by conghuyn** [comment]
> Hey @huync16! 👋🏻
> 
> Could you please make a PR?

Sure!
